export const LOAD_COIN_DETAIL_PAGE = 'VF/App/LOAD_COINS_DETAIL_PAGE';
export const LOAD_COIN_DETAIL_PAGE_SUCCESS =
  'VF/App/LOAD_COINS_DETAIL_PAGE_SUCCESS';
export const LOAD_COIN_DETAIL_PAGE_ERROR =
  'VF/App/LOAD_COINS_DETAIL_PAGE_SUCCESS';
